[workspace]
members = [
	"client/consensus/nimbus-consensus",
	"pallets/aura-style-filter",
	"pallets/author-inherent",
	"pallets/author-slot-filter",
	"parachain-template/node",
	"parachain-template/runtime",
	"primitives/nimbus-primitives",
]

[profile.release]
panic = "unwind"
